create table if not exists public.admin_activity_log (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  match_event_id bigint,
  admin_user_id uuid not null,
  action text not null check (action in ('created', 'updated', 'corrected', 'deleted')),
  event_type text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_activity_log_match_created_idx
  on public.admin_activity_log (match_id, created_at desc);

alter table public.admin_activity_log enable row level security;
revoke all on table public.admin_activity_log from anon, authenticated;
grant all on table public.admin_activity_log to service_role;
grant usage, select on sequence public.admin_activity_log_id_seq to service_role;

drop policy if exists "No client access to admin activity" on public.admin_activity_log;
create policy "No client access to admin activity"
  on public.admin_activity_log
  for all
  to public
  using (false)
  with check (false);

create or replace function private.log_match_event_activity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_id uuid := auth.uid();
  event_row public.match_events;
  activity_action text;
  activity_details jsonb;
begin
  if actor_id is null then
    return null;
  end if;

  if tg_op = 'INSERT' then
    event_row := new;
    activity_action := 'created';
    activity_details := jsonb_build_object(
      'team_id', new.team_id,
      'player_id', new.player_id,
      'player_off_id', new.player_off_id,
      'player_on_id', new.player_on_id,
      'match_minute', new.match_minute,
      'notes', new.notes
    );
  elsif tg_op = 'UPDATE' then
    event_row := new;
    activity_action := 'updated';
    activity_details := jsonb_build_object(
      'before', jsonb_build_object(
        'team_id', old.team_id,
        'player_id', old.player_id,
        'player_off_id', old.player_off_id,
        'player_on_id', old.player_on_id,
        'match_minute', old.match_minute,
        'notes', old.notes
      ),
      'after', jsonb_build_object(
        'team_id', new.team_id,
        'player_id', new.player_id,
        'player_off_id', new.player_off_id,
        'player_on_id', new.player_on_id,
        'match_minute', new.match_minute,
        'notes', new.notes
      )
    );
  else
    event_row := old;
    activity_action := 'deleted';
    activity_details := jsonb_build_object(
      'team_id', old.team_id,
      'player_id', old.player_id,
      'player_off_id', old.player_off_id,
      'player_on_id', old.player_on_id,
      'match_minute', old.match_minute,
      'notes', old.notes
    );
  end if;

  insert into public.admin_activity_log (
    match_id,
    match_event_id,
    admin_user_id,
    action,
    event_type,
    details
  ) values (
    event_row.match_id,
    event_row.id,
    actor_id,
    activity_action,
    event_row.event_type,
    activity_details
  );

  return null;
end;
$$;

drop trigger if exists log_match_event_activity on public.match_events;
create trigger log_match_event_activity
after insert or update or delete on public.match_events
for each row execute function private.log_match_event_activity();

revoke all on function private.log_match_event_activity() from public, anon, authenticated;
